name: Deploy to VPS

on:
  push:
    branches:
      - main  # or master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy with appleboy/ssh-action
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
      script: |
        cd /var/www/next-intl
        git pull origin main
        npm install
        npm run build
        pm2 restart nextjs-app